name: AppSignal CI

on:
  pull_request:
    paths:
      - 'experimental/appsignal/**'
      - '.github/workflows/appsignal-ci.yml'

jobs:
  functional-tests:
    name: AppSignal Functional Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: experimental/appsignal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm run install-all

      - name: Build project
        run: npm run build

      - name: Run functional tests
        run: npm run test:run -- --reporter=json --reporter=default --outputFile=test-results.json
        env:
          APPSIGNAL_API_KEY: test-api-key
          APPSIGNAL_APP_ID: test-app-id

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: functional-test-results
          path: experimental/appsignal/test-results.json
          retention-days: 7

  integration-tests:
    name: AppSignal Integration Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: experimental/appsignal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install shared dependencies
        run: cd shared && npm install

      - name: Install local dependencies
        run: cd local && npm install

      - name: Install test-mcp-client dependencies
        run: cd ../../test-mcp-client && npm install

      - name: Run integration tests
        run: npm run test:integration
        env:
          APPSIGNAL_API_KEY: test-api-key
          APPSIGNAL_APP_ID: test-app-id
