name: AppSignal MCP Server CI

on:
  push:
    branches:
      - main
    paths:
      - 'experimental/appsignal/**'
      - '.github/workflows/appsignal-ci.yml'
  pull_request:
    paths:
      - 'experimental/appsignal/**'
      - '.github/workflows/appsignal-ci.yml'

jobs:
  functional-tests:
    name: AppSignal MCP Server Functional Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: experimental/appsignal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci && npm run install-all

      - name: Build project
        run: npm run build

      - name: Install and build test-mcp-client
        run: cd ../../test-mcp-client && npm install && npm run build

      - name: Run functional tests
        run: npm run test:run -- --reporter=json --reporter=default --outputFile=test-results.json
        env:
          APPSIGNAL_API_KEY: test-api-key
          APPSIGNAL_APP_ID: test-app-id

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: functional-test-results
          path: experimental/appsignal/test-results.json
          retention-days: 7

  integration-tests:
    name: AppSignal MCP Server Integration Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: experimental/appsignal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Install shared dependencies
        run: cd shared && npm ci

      - name: Install local dependencies
        run: cd local && npm ci

      - name: Install test-mcp-client dependencies
        run: cd ../../test-mcp-client && npm ci

      - name: Build test-mcp-client
        run: cd ../../test-mcp-client && npm run build

      - name: Run integration tests
        run: npm run test:integration
        env:
          APPSIGNAL_API_KEY: test-api-key
          APPSIGNAL_APP_ID: test-app-id

  integration-published-tests:
    name: AppSignal MCP Server Integration Tests (Published Build)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: experimental/appsignal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Install shared dependencies
        run: cd shared && npm ci

      - name: Install local dependencies
        run: cd local && npm ci

      - name: Install test-mcp-client dependencies
        run: cd ../../test-mcp-client && npm ci

      - name: Build test-mcp-client
        run: cd ../../test-mcp-client && npm run build

      - name: Run published integration tests
        run: npm run test:integration-published
        env:
          APPSIGNAL_API_KEY: test-api-key
          APPSIGNAL_APP_ID: test-app-id
