name: AppSignal CI

on:
  pull_request:
    paths:
      - 'experimental/appsignal/**'
      - '.github/workflows/appsignal-ci.yml'

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: experimental/appsignal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install root dependencies
        run: |
          cd ../.. && npm install
          cd experimental/appsignal

      - name: Install dependencies
        run: npm run install-all

      - name: Build project
        run: npm run build

      - name: Lint code
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Type check
        run: |
          cd shared && npx tsc --noEmit
          cd ../local && npx tsc --noEmit

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    needs: lint-and-type-check

    defaults:
      run:
        working-directory: experimental/appsignal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm run install-all

      - name: Build project
        run: npm run build

      - name: Run functional tests
        run: npm run test:run -- --reporter=json --reporter=default --outputFile=test-results.json
        env:
          APPSIGNAL_API_KEY: test-api-key
          APPSIGNAL_APP_ID: test-app-id

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: functional-test-results
          path: experimental/appsignal/test-results.json
          retention-days: 7

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: lint-and-type-check

    defaults:
      run:
        working-directory: experimental/appsignal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install shared dependencies
        run: cd shared && npm install

      - name: Install local dependencies
        run: cd local && npm install

      - name: Install test-mcp-client dependencies
        run: cd ../../test-mcp-client && npm install

      - name: Run integration tests
        run: npm run test:integration
        env:
          APPSIGNAL_API_KEY: test-api-key
          APPSIGNAL_APP_ID: test-app-id

  # This job runs after all tests pass
  all-checks-passed:
    name: All CI Checks Passed
    runs-on: ubuntu-latest
    needs: [lint-and-type-check, functional-tests, integration-tests]
    if: always()

    steps:
      - name: Check if all jobs passed
        run: |
          if [[ "${{ needs.lint-and-type-check.result }}" == "success" && "${{ needs.functional-tests.result }}" == "success" && "${{ needs.integration-tests.result }}" == "success" ]]; then
            echo "✅ All CI checks passed!"
            exit 0
          else
            echo "❌ One or more CI checks failed"
            echo "Lint and Type Check: ${{ needs.lint-and-type-check.result }}"
            echo "Functional Tests: ${{ needs.functional-tests.result }}"
            echo "Integration Tests: ${{ needs.integration-tests.result }}"
            exit 1
          fi
